### ISSUE TITLE
[JOSS] File path in user manual

### ISSUE THREAD

**Issue by EwaGomez** [CLOVER-energy/CLOVER#134]
In your CLOVER user manual it is stated that you manually have to change the file path in different files. That seems very inconvenient, have you thought about automating that? In my recent PV simulation tool I used path from pathlib.
This could be an example of setting the path, where CLOVER is installed as the rootPath.

> from pathlib import Path
> rootPath = os.path.realpath(".")
 

It seems that the user manual is not as actual as the ReadMe, am I right? So if that might not me an issue anymore, please update the user manual.

cross-reference: #openjournals/joss-reviews/issues/4799

**Comment by phil-sandwell** [comment]
Thanks very much for highlighting this. The present version of CLOVER (v5) has addressed this issue, whilst the user manual refers to the process required in v4. For new users we recommend referring to the ReadMe and Wiki as the primary sources of guidance on how to use CLOVER, rather than the old user manual which has become somewhat redundant. 

To address this we have moved the old user manual to an `archive` folder (#137) which should clarify this, whilst still being available for reference if required.

**Comment by EwaGomez** [comment]
Thank you @phil-sandwell for the fast implementation!

**Comment by phil-sandwell** [comment]
Thank you @EwaGomez, and thanks @BenWinchester too for handling this!
