### ISSUE TITLE
Variable reassignment

### ISSUE THREAD

**Issue by BenWinchester** [CLOVER-energy/CLOVER#75]
### Describe the bug
The `get_diesel_fuel_usage` function reassigns variables. The behaviour of this, and whether the function is behaving as expected, has not been verified. This verification is needed to confirm whether this is a bug.

### Desktop
**(please complete the following information)**
 - OS: This affects all operating systems :penguin: :apple: 🏁 
 - Installation setup: All
 - Version: `5.0.0` onwards
 - Branch: All branches affected.

### Code snippet
A snippet of the relevant function:
```
def get_diesel_fuel_usage(
    capacity: int,
    diesel_generator: DieselGenerator,
    diesel_energy: pd.DataFrame,
    diesel_times: pd.DataFrame,
) -> pd.DataFrame:
    """
    Find diesel fuel consumption.

    Calculates the fuel usage of the diesel backup generator

    Inputs:
        - capacity:
            Capacity (kW) of the diesel generator.
        - diesel_generator:
            The diesel backup generator being modelled.
        - diesel_energy:
            Profile of energy supplued by diesel backup.
        - diesel_times:
            Profile of times when generator is on (1) or off (0).

    Outputs:
        - fuel_usage:
            Hourly profile of diesel fuel usage (litres).

    """

    load_factor: pd.DataFrame = diesel_energy.divide(capacity)  # type: ignore
    above_minimum = pd.DataFrame(
        load_factor.values * (load_factor > diesel_generator.minimum_load).values
    )
    below_minimum = (
        load_factor <= diesel_generator.minimum_load
    ) * diesel_generator.minimum_load
    load_factor = pd.DataFrame(
        diesel_times.values * (above_minimum.values + below_minimum.values)
    )

    fuel_usage: pd.DataFrame = (
        load_factor * capacity * diesel_generator.diesel_consumption
    )
    fuel_usage = fuel_usage.astype(float)

    return fuel_usage
```

**Comment by phil-sandwell** [comment]
This is lazy coding by me. The variable `load_factor` is used twice:

1. To calculate the load factor of the diesel generator which would be necessary to meet the electricity demand, then
2. To recalculate it after including the condition that the load factor cannot be below `minimum_load`. This is a physical condition imposed on real-life diesel generators to avoid damage caused by operating at low loads, which increases maintenance issues and general wear and tear. 

We could change the second `load_factor` to something like `safe_load_factor` along the lines of:

`safe_load_factor = pd.DataFrame(
        diesel_times.values * (above_minimum.values + below_minimum.values)`

`    fuel_usage: pd.DataFrame = (
        safe_load_factor * capacity * diesel_generator.diesel_consumption
    )`

I don't think this will introduce any issues, and if it does these should be picked up by the new tests. What do you think?

**Comment by BenWinchester** [comment]
This isn't an issue and has now been fixed on the `dev` branch 😄
